server:
  port: 8081

spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:~/food
    username: root
    password: root
    driver-class-name: org.h2.Driver
  h2:
    console:
      enabled: true
      path: /h2
  flyway:
    url: jdbc:h2:~/food
    user: ${DATABASE_USER:root}
    password: ${DATABASE_PASSWD:root}
    enabled: true